# 1. Load the CSV using Pandas and display the first 10 rows.

In [15]:
import pandas as pd
df = pd.read_csv("C:\\Users\\deore\\Downloads\\customer_data - customer_data.csv")
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

# 2. Check the number of rows and columns in the dataset.

In [16]:
df.shape

(2000, 15)

# 3. Display all column names and identify which column names contain  leading/trailing spaces or inconsistent capitalization.

In [17]:
df.columns = df.columns.str.title()

In [19]:
df.head()

,Customer Id,Age,Income_Usd,Credit Score,Tenure_Years,Monthly_Visits,Satisfaction,City,Customer_Segment,Gender,Is_Active,Churn_Flag,Signup_Date,Lead_Source,Notes_Text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???

# 4. Check the data type of every column using Pandas.

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer Id       1980 non-null   object
 1   Age               1669 non-null   object
 2   Income_Usd        1560 non-null   object
 3   Credit Score      1640 non-null   object
 4   Tenure_Years      1742 non-null   float64
 5   Monthly_Visits    1720 non-null   float64
 6   Satisfaction      1601 non-null   float64
 7   City              1700 non-null   object
 8   Customer_Segment  1620 non-null   object
 9   Gender            1760 non-null   object
 10  Is_Active         1660 non-null   object
 11  Churn_Flag        1840 non-null   object
 12  Signup_Date       1760 non-null   object
 13  Lead_Source       1580 non-null   object
 14  Notes_Text        1344 non-null   object
dtypes: float64(3), object(12)
memory usage: 234.5+ KB

In [22]:
df.dtypes

Customer Id          object
Age                  object
Income_Usd           object
Credit Score         object
Tenure_Years        float64
Monthly_Visits      float64
Satisfaction        float64
City                 object
Customer_Segment     object
Gender               object
Is_Active            object
Churn_Flag           object
Signup_Date          object
Lead_Source          object
Notes_Text           object
dtype: object

# 5. Calculate the number and percentage of missing values in every column.

In [26]:
# number of missing values
missing_values = df.isna().sum()
missing_values

Customer Id          20
Age                 331
Income_Usd          440
Credit Score        360
Tenure_Years        258
Monthly_Visits      280
Satisfaction        399
City                300
Customer_Segment    380
Gender              240
Is_Active           340
Churn_Flag          160
Signup_Date         240
Lead_Source         420
Notes_Text          656
dtype: int64

In [24]:
# percentage of missing values
miss_per = (missing_values / len(df))*100

In [25]:
miss_per

Customer Id          1.00
Age                 16.55
Income_Usd          22.00
Credit Score        18.00
Tenure_Years        12.90
Monthly_Visits      14.00
Satisfaction        19.95
City                15.00
Customer_Segment    19.00
Gender              12.00
Is_Active           17.00
Churn_Flag           8.00
Signup_Date         12.00
Lead_Source         21.00
Notes_Text          32.80
dtype: float64

# 6. Find the rows where Customer ID is missing.

In [36]:
miss = df[df['Customer Id'].isnull()]
miss.index

Index([ 162,  226,  300,  421,  770,  821,  876,  993, 1023, 1188, 1202, 1212,
       1248, 1338, 1346, 1448, 1451, 1462, 1564, 1652],
      dtype='int64')

# 7. Remove leading/trailing whitespace from all column names and convert them  to lowercase with underscores.

In [47]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [48]:
df.rename({'customer id':'customer_id'},inplace = True)

In [49]:
df.head()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???

# 8. Identify duplicate Customer ID values and count how many duplicates exist.

In [69]:
df['customer_id'].duplicated().sum()

np.int64(19)

In [70]:
dub=df[df['customer_id'].duplicated()]
dub.index

Index([ 226,  300,  421,  770,  821,  876,  993, 1023, 1188, 1202, 1212, 1248,
       1338, 1346, 1448, 1451, 1462, 1564, 1652],
      dtype='int64')

# 9. Remove duplicate customer records while keeping the first occurrence

In [75]:
df = df.drop_duplicates(subset ='customer_id' ,keep = 'first')
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,M,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,SMB,m,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,SMB.,F,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,SMB,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

# 10. Find all unique values in the customer_segment column and identify  inconsistent categories such as Consumer, consumer, consumer , etc.

In [84]:
df['customer_segment'].value_counts()

customer_segment
Consumer      661
SMB           390
Enterprise    290
consumer      118
UNKNOWN        76
SMB.           68
Name: count, dtype: int64

In [95]:
# before
df['customer_segment'].unique()

array(['Consumer', 'Enterprise', 'Smb', nan], dtype=object)

# 11.Clean the customer_segment column by standardizing capitalization and  whitespace.

In [96]:
import numpy as np
df['customer_segment'] = (df['customer_segment'].str.strip()
                          .str.replace('.',' ',regex=False)
                          .str.title()
                          .replace('Unknown',np.nan)
                          .str.strip()
                         )

In [97]:
# after
df['customer_segment'].unique()

array(['Consumer', 'Enterprise', 'Smb', nan], dtype=object)

In [98]:
df['customer_segment'].value_counts()

customer_segment
Consumer      779
Smb           458
Enterprise    290
Name: count, dtype: int64

# 12.Find all unique values in the gender column and convert them into consistent  categories such as Male and Female.

In [102]:
df['gender'].unique()

array([nan, 'Male', 'm', 'Female', 'M', 'F', 'f'], dtype=object)

In [101]:
df['gender'].value_counts()

gender
m         314
Male      300
F         293
f         285
Female    283
M         267
Name: count, dtype: int64

In [108]:
df['gender'] = ( df['gender'].str.strip()
                 .replace({'m':'Male',
                               'F':'Female',
                               'f':'Female',
                               'M':'Male',
                                }))

In [110]:
df

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,Consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,Male,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,Male,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.26951178,79436.89335,633.9740063,14.007477,NaN,3.556073,Bengaluru,Consumer,Male,no,No,2024-02-26,email,normal
1996,CUST-01295,41.09168505,39912.37991,701.7201056,0.673289,8.0,2.963094,Pune,Smb,Male,N,Yes,2024-08-11,Website,good
1997,CUST-00861,26.21576696,24522.26545,647.7993363,2.026485,12.0,3.079259,Hyderabad,Smb,Female,yes,No,2023-05-27,WEB,???
1998,CUST-01460,42.3 years,84103.61056,521 pts,7.168156,5.0,3.579652,Hyderabad,Smb,NaN,N,Yes,2025-01-26,Email,ok
1999,CUST-01127,59.25609491,53723.87392,576.7390735,9.720663,NaN,1.100520,Pune,Consumer,NaN,yes,No,2024-02-22,???,good

# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and  No, no, N, 0 become 0.

In [114]:
df['is_active'].dtype

dtype('O')

In [113]:
df['is_active'].value_counts()

is_active
Yes    226
1      220
No     217
N      210
yes    200
Y      195
no     189
0      186
Name: count, dtype: int64

In [116]:
df['is_active'].unique()

array(['Yes', nan, 'N', 'yes', 'No', 'no', 'Y', '1', '0'], dtype=object)

In [117]:
df['is_active'] = ( df['is_active'].str.strip()
                    .str.lower()
                    .replace({'n':'no',
                             'y':'yes',
                             '1':'yes',
                             '0':'no'})
                    .str.title())

In [118]:
df['is_active'].unique()

array(['Yes', nan, 'No'], dtype=object)

In [119]:
df['is_active']

0       Yes
1       NaN
2       Yes
3        No
4       Yes
       ...
1995     No
1996     No
1997    Yes
1998     No
1999    Yes
Name: is_active, Length: 1981, dtype: object

# 14.Convert the churn_flag column from categorical values (Yes/No) into a binary  numerical column (1/0).

In [121]:
df['churn_flag'].dtype

dtype('O')

In [126]:
df['churn_flag'].isna().sum()

np.int64(157)

In [124]:
df['churn_flag'].value_counts()

churn_flag
No     1383
Yes     441
Name: count, dtype: int64

In [125]:
df['churn_flag'].unique()

array(['No', 'Yes', nan], dtype=object)

In [128]:
df['churn_flag'] = (df['churn_flag'].str.strip()
                    .replace({'No':'0',
                             'Yes':'1'}))

In [129]:
df['churn_flag'].value_counts()

churn_flag
0    1383
1     441
Name: count, dtype: int64

# 15.Identify all values in income_usd that cannot be directly interpreted as  numbers.

In [149]:
df['income_usd'].dtype

dtype('O')

In [150]:
hed = df['income_usd'].value_counts()
hed.head(12)

income_usd
₹55k           9
$41,941        2
28198.41033    1
45187.26964    1
27969.20593    1
38331.26288    1
37388.43249    1
54966.13884    1
$42,625        1
39190.5987     1
62319.39692    1
$93,193        1
Name: count, dtype: int64

In [151]:
df['income_usd'].unique()

array(['28198.41033', '61312.83129', '44199.67124', ..., '24522.26545',
       '84103.61056', '53723.87392'], shape=(1517,), dtype=object)

In [152]:
invalid_income = df[pd.to_numeric(df['income_usd'], errors='coerce').isna()] 
print(invalid_income['income_usd'].unique())

['$44,696' '$41,941' nan '$123,682' '$40,978' '$45,565' '$112,864'
 '$38,946' '$93,738' '$70,056' '$26,771' '$48,959' '$36,410' '$86,520'
 '$88,847' '$88,960' '$50,211' '$104,630' '$72,142' '$34,864' '$130,837'
 '$90,730' '$29,657' '$60,407' '₹55k' '$506,709' '$71,214' '$191,997'
 '$35,341' '$171,139' '$65,761' '$30,152' '$47,631' '$319,924' '$46,216'
 '$49,366' '$78,703' '$44,955' '$76,860' '$50,094' '$129,799' '$32,702'
 '$33,399' '$19,760' '$146,497' '$30,746' '$107,324' '$19,808' '$49,885'
 '$22,575' '$53,462' '$100,254' '$37,397' '$89,920' '$60,643' '$153,576'
 '$114,703' '$117,570' '$155,204' '$39,065' '$108,002' '$33,428' '$18,612'
 '$32,495' '$31,099' '$60,008' '$31,588' '$84,034' '$92,205' '$30,921'
 '$38,009' '$61,792' '$48,656' '$49,855' '$23,569' '$38,605' '$37,860'
 '$47,580' '$24,527' '$78,202' '$53,993' '$64,415' '$99,869' '$543,686'
 '$74,109' '$45,886' '$75,683' '$59,291' '$41,955' '$37,026' '$13,148'
 '$56,234' '$73,642' '$44,722' '$39,362' '$41,269' '$33,259' '$34,160'
 '$45,415' '$55,242' '$35,506' '$352,568' '$25,393' '$20,322' '$65,732'
 '$15,187' '$61,230' '$38,916' '$97,960' '$93,193' '$42,625' '$36,305'
 '$33,715' '$34,982' '$45,435' '$212,590' '$151,415' '$38,849' '$256,510'
 '$25,921' '$52,112' '$155,352' '$45,288' '$76,139' '$48,047' '$27,675'
 '$55,161' '$63,822' '$124,103' '$26,579' '$27,606' '$87,822' '$83,857'
 '$31,808' '$24,295' '$22,540' '$38,251' '$41,234' '$506,702' '$52,352'
 '$31,857' '$98,449' '$54,157' '$49,817' '$17,863' '$160,831' '$119,220'
 '$264,787' '$69,968' '$105,759' '$76,027' '$24,407' '$135,870' '$40,483'
 '$68,496' '$53,034' '$50,179' '$41,996' '$295,916' '$100,739' '$64,975'
 '$64,537' '$30,668' '$47,068' '$51,813' '$57,778' '$50,057' '$125,589'
 '$22,832' '$58,551' '$135,575' '$34,809' '$80,389' '$58,046']

In [167]:

f = lambda x: d if d.startwit('$')

SyntaxError: expected 'else' after 'if' expression (1890707006.py, line 2)

# 16.Clean income_usd by removing currency symbols, commas, and invalid text,  then convert it to a numeric column using pd.to_numeric().

In [143]:
df['income_usd'].dtypes

dtype('O')

In [162]:
df['income_usd'] = (
    df['income_usd']
    .str.strip()                         
    .str.replace('$', '', regex=False)  
    .str.replace('₹', '', regex=False) 
    .str.replace(',', '', regex=False) 
    .str.replace('k', '000', regex=False)  
)

In [164]:
df['income_usd'].value_counts()

income_usd
55000          9
41941          2
28198.41033    1
45187.26964    1
27969.20593    1
              ..
44710.3978     1
62852.30032    1
33360.89659    1
60908.05938    1
53723.87392    1
Name: count, Length: 1516, dtype: int64