## 1. Load the dataset using the appropriate Pandas method and store it in a  variable named df.

In [6]:
import pandas as pd
df = pd.read_excel("C:\\Users\\deore\\Downloads\\Bank_customer_churn.xlsx")

## 2. Display the first 8 rows of the dataset.

In [7]:
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

## 3. Display the last 12 rows of the dataset.

In [8]:
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## 4. Show 10 random rows from the dataset.

In [9]:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
7008,7009,15638610,Kennedy,635,Germany,Female,65,5,117325.54,1,1,0,155799.86,1
4044,4045,15607142,Parkin,658,France,Male,32,8,0.00,1,1,1,80410.68,0
3672,3673,15706904,Robertson,750,France,Male,43,6,113882.31,1,1,1,74564.41,0
965,966,15602084,Coles,663,France,Female,42,5,124626.07,1,1,1,78004.50,0
7743,7744,15741643,Chiang,777,Germany,Male,35,7,122917.69,1,1,1,76169.68,0
9172,9173,15652615,Ferri,742,France,Male,39,8,140004.96,1,1,1,92985.78,0
3502,3503,15660505,Romani,735,Germany,Male,46,2,106344.95,1,1,0,114371.33,1
29,30,15656300,Lucciano,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
3130,3131,15813113,Chang,795,Spain,Female,56,5,0.00,1,1,0,35418.69,1

## 5. Find the shape of the dataset.

In [11]:
df.shape

(10000, 14)

## 6. Display complete information about the dataset using one method.  o Number of non-null values  
o Data types  
o Memory usage

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

## 7. Print the names of all columns in the dataset.

In [15]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

## 8. Find the data type of every column.

In [17]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

## 9. Check for missing values in every column using:  
o isnull().sum()  
o isna().sum()

In [19]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [21]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

## 10.Select only one column:

In [24]:
target = df['CreditScore']
target

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

## 11.Select the following multiple columns:

In [27]:


target = df[["CustomerId","Surname","Balance","Exited"]]

target

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

## 12.Display only numeric columns using select_dtypes().

In [30]:
int_column = df.select_dtypes(include = ["int64"]).columns
len(int_column)

9

## 13.Generate the statistical summary of all numeric columns using describe().

In [33]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

## 14.Check for duplicate rows in the dataset.  
o How many duplicate rows exist? 
o Remove all duplicate rows.

In [35]:
df.duplicated().sum()

np.int64(0)

In [37]:
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

## 15.Count the number of customers in each class of the Exited column using  value_counts()

In [39]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

# Operators + Loops (1-5)

## 1. Take two numbers from user. Perform all arithmetic operations and also check  which number is greater using comparison operators.

In [42]:
LIST = []
n1 = int(input("Enter any number"))
n2 = int(input("Enter any number:"))

print(LIST.append(n1+n2))
print("Addition is :",LIST[0])
print(LIST.append(n1-n2))
print("substraction is :",LIST[1])
print(LIST.append(n1*n2))
print("Multiplication is :",LIST[2])
print(LIST.append(n1/n2))
print("divisionn is :",LIST[3])
print(LIST.append(n1//n2))
print("Floor division :",LIST[4])
print(LIST.append(n1%n2))
print("Remender is :",LIST[5])
print(LIST.append(n1**n2))
print("Power is :",LIST[6])

gratter = LIST[0]

for i in LIST:
    if i > gratter:
        gratter = i

print("Gratter calculation is :",gratter)

Enter any number 8
Enter any number: 2

None
Addition is : 10
None
substraction is : 6
None
Multiplication is : 16
None
divisionn is : 4.0
None
Floor division : 4
None
Remender is : 0
None
Power is : 64
Gratter calculation is : 64

## 2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop  completely when number 40 is reached using break.

In [46]:
for i in range(1,50):
    if i == 40:
        break
    elif i % 5 == 0:
        continue
    else:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

## 3. Take numbers from user until they enter negative number. Calculate sum and  average using while loop.

In [47]:
Sum = 0
count = 0

while True:
    num = int(input())
    if num < 0:
        break
    Sum +=num
    count+=1

print("Sum:",Sum)
print("Average",Sum/count)

 3
 3
 5
 6
 7
 4
 3
 -1

Sum: 31
Average 4.428571428571429

## 4. Print the following pattern using nested loops: 
***** 
**** 
*** 
** 
*

In [48]:
for i in range(5,0,-1):
    print("*" * i)

*****
****
***
**
*

## 5. Find the factorial of a number using for loop and also using while loop.

In [51]:
number = int(input())
fact = 1
for i in range(number,1,-1):
    fact *=i
print(fact)

 3

6

## Data Types & Methods (6-9)

## 6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace  spaces with -, and check if it starts with “Hello”.

In [54]:
String = input()
print(String.upper())
print(String.count("a"))
print(String.replace(" ","-"))
print(String.startswith("Hello"))

 Hello my name is yash

HELLO MY NAME IS YASH
2
Hello-my-name-is-yash
True

## 7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)  and reverse.

List = []

for i in range(0,6):
    List.append(int(input()))

print("original List:",List)
List.insert(0,10)
print("Insert 10",List)
List.remove(4)
print("Remove 4",List)
List.pop()
print("Pop last element",List)
List.sort(reverse = True)
print("desending order",List)
List.sort()
print("assending order",List)

## 8. Create a dictionary of 4 students (name:marks). Print only those students who  scored more than 80 using items().

In [ ]:
Dict = {"Yash":55 , "Rohit" : 78 ,"Prashant" : 99 , "Tanu" : 88}

for i,j in Dict.items():
    if j > 80:
        print(f"{i} : {j}")


## 9. Create two sets and perform union, intersection, difference. Also add and discard  elements.

In [7]:
set1 = {1,2,9,4,5}
set2 = {1,2,3,4,5,6,7,8}

print(set1.union(set2))
print(set1.intersection(set2))
print(set2.difference(set1))

{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 4, 5}
{8, 3, 6, 7}

# OOP + Encapsulation (10-14)

## 10. Create a class Student with private attribute __marks. Add getter and setter with  validation (0–100).

In [11]:
class Student:
    def __init__(self,marks):
        self.__marks=marks

    def get_marks(self):
        return self.__marks

    def set_marks(self,mar):
        if 0 <= mar <= 100:
            self.__marks = mar
        else:
            print("Marks is not in between 0 to 100")

obj = Student(88)
obj.set_marks(0)

## 11. Create class BankAccount with private __balance. Add deposit and withdraw  methods. Raise custom exception if balance becomes negative

In [16]:
class NegativeNumberError(Exception):
    pass
    
class BankAccount:
    def __init__(self,balance):
        self.__balance = balance

    def deposit(self):
        amount  = int(input("Enter amount for deposit:"))
        if amount > 0:
            self.__balance += amount
            print(f"{amount} is added successfully and your balance is {self.__balance}")
            
        else:
            raise NegativeNumberError("You enter the negative number ")

    def withdraw(self):
        amount  = int(input("Enter amount for withdraw:"))
        if amount > 0:
            if self.__balance > amount :
                self.__balance -= amount
                print(f"{amount} is withdraw successfully and your balance is {self.__balance}")
            
            else:
                print("insafficient balance")
        else:
            raise NegativeNumberError("You enter the negative number ")


try :

    obj = BankAccount(12000)
    obj.deposit()
    obj.withdraw()

except NegativeNumberError as e:
    print(e)

Enter amount for deposit: 4

4 is added successfully and your balance is 12004

Enter amount for withdraw: -1

You enter the negative number

## 12. Create class Employee with class attribute company_name. Show that it is  shared by all objects. Also update the class attribute.

In [17]:
class Employee:
    complany_name = "TCS"
    def __init__(self,name):
        self.name = name

    def display(self):
        print("Name:",self.name)
        print("Complany name:",Employee.complany_name)

obj = Employee("Yash")
obj1 = Employee("Rohit")


obj.display()
obj1.display()

Name: Yash
Complany name: TCS
Name: Rohit
Complany name: TCS

## 13. Create class Product with private __price. Add getter and setter. Setter should  not allow price less than 100.

In [ ]:
class Product:
    def __init__(self,price):
        self.__price = price

    def get_price(self):
        return self.__price

    def set_price(self,new_price):
        if new_price > 100:
            self.__price = new_price
        else:
            print("Price is above 100")

## 14. Create class Rectangle with private length and width. Add method to calculate  area and perimeter

In [22]:
class Rectangle:
    def __init__(self,length,width):
        self.__length = length 
        self.__width = width

    def area(self):
        print("Area of Rectangel:",self.__length * self.__width)

    def perimeter(self):
        print("Parameter of the rectange:",2*(self.__length + self.__width))


obj = Rectangle(2,4)
obj.area()

Area of Rectangel: 8


## Inheritance + Abstraction + super() (15-19)

## 15. Create single level inheritance: Person → Student. Use super() in constructor.

In [ ]:
class Person:
    def __init__(self,name):
        self.name = name

    def show(self):
        return f"Name : {self.name}"
        
class Student(Person):
    def __init__(self,name,age):
        super().__init__(name)
        self.age = age

    def display(self):
        print(super().show())
        print("age :",self.age)


obj =Student("Yash",22)
obj.display()